# _config.yml
title: Your Name
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Your UX Research Portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://username.github.io" # the base hostname & protocol for your site
